- apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
- apt_repository:
    repo: 'deb https://deb.nodesource.com/node_7.x xenial main'
    state: present
- apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - nodejs
    - npm
    - git