- include_vars: "{{ ansible_os_family }}.yml"

- include: "{{ ansible_os_family }}.yml"
  become: yes

- name: create {{node_user}} group
  group: name={{node_user}} state=present
  become: yes

- name: create {{node_user}} user
  user: name={{node_user}} groups={{node_user}} state=present
  become: yes

- name: make a folder
  file:
    path: "{{item}}"
    state: directory
    owner: "{{node_user}}"
    group: "{{node_user}}"
  become: yes
  with_items:
    - "/usr/local/{{node_app_name}}"
    - "/var/log/{{node_app_name}}"